version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging / auth in to Amazon ECR
       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382546373.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - echo Building the docker image
      - docker build -t sample-nodejs-image .
      - docker tag sample-nodejs-image:latest 992382546373.dkr.ecr.us-east-1.amazonaws.com/sample-nodejs-image:latest


  post_build:
    commands:
     - echo build completed
     - echo pushing in to docker ECR...
     - docker push 992382546373.dkr.ecr.us-east-1.amazonaws.com/sample-nodejs-image:latest
     - echo Writing image definition file..
     - printf '[{"name":"%s","imageUri":"%s"}]' "sample-nodejs-app" "992382546373.dkr.ecr.us-east-1.amazonaws.com/sample-nodejs-image" > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
